phrase:
  project_id: 7c51854dc58be9e325dd20c026488de6
  push:
    sources:
    - file: ./sample.po
      params:
        locale_id: en
        update_translations: false
        file_format: gettext
  pull:
    targets:
    - file: ./<locale_name>/sample.po
      params:
        file_format: gettext
