phrase:
  access_token: 154d8ddb36e4c4912c498fe249e51db71711f09c9fb6938467845e593dacf954
  project_id: 2736743742346691b29873dbb96ef1a4
  push:
    sources:
    - file: ./sample.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./sample_translated.json
      params:
        file_format: simple_json
