phrase:
  project_id: 0af267ad39dba7798f90c3493401c7c4
  push:
    sources:
    - file: ./sample.po
      params:
        locale_id: en
        update_translations: true
        file_format: gettext
  pull:
    targets:
    - file: ./<locale_name>/sample.po
      params:
        file_format: gettext
